language: ruby
rvm:
  - 1.9.3
  - rbx-19mode
  - jruby-19mode
env:
  - DB=mysql
  - DB=postgres
gemfile:
  - Gemfile
  - ci/gemfiles/rspec2_11_rails3_2.gemfile
  - ci/gemfiles/rspec2_11_rails3_1.gemfile
  - ci/gemfiles/rspec2_11_rails3_0.gemfile
before_script:
  - ci/script/create_db.sh
  - bundle exec rake db:test:reset --trace
script: bundle exec rspec -b
